### PR TITLE
feat: ember@4 support

### PR DESCRIPTION
**Pull request by matthewhartstonge**
@mansona it builds... 
Haven't got to the point of running codemods/testing it yet as I just needed our apps to compile on ember@5 before circling back to upgrading/fixing `ember-paper`

### CODE REVIEW

**Comment by mansona** [comment]
ooo nice one! 🎉 it looks like we're both thinking the same thing at the moment 😂

**Comment by matthewhartstonge** [comment]
oop, looks like I need to merge in upstream..

**Comment by matthewhartstonge** [comment]
Do you have contrib access to `ember-css-transistions`?
There is a bug in the repo that needs to be fixed:

- utils aren't exported in the dist
- the github action needs to be upgraded to strip the `prepare` script from the output `package.json` otherwise it gets run when npm imported, causing a failure. 

https://github.com/miguelcobain/ember-css-transitions/compare/master...matthewhartstonge:ember-css-transitions:master?expand=1

**Comment by mansona** [comment]
I don't have access to ember-css-transitions no, but it looks like it's active enough so I wouldn't worry about opening up a PR there.

Why are you asking about utils though? It looks like the deployed version of the package is inlining the utils imports in the dist: https://unpkg.com/browse/ember-css-transitions@4.4.0/dist/modifiers/css-transition.js#L44

**Comment by matthewhartstonge** [comment]
omg... you're kidding...
There's no changelog, so I couldn't easily track the breaking changes.

Righto, all of these will be an easy change then!! one momento..

- https://github.com/miguelcobain/ember-paper/blob/77733455921bec810d2f1207da9eb35bc3ed6a0a/addon/components/paper-ripple/component.js#L8
- https://github.com/miguelcobain/ember-paper/blob/4a560c8a2b8de54f367b60d55dc19b35ce1b63e0/addon/components/paper-menu/content/component.js#L6
- https://github.com/miguelcobain/ember-paper/blob/4a560c8a2b8de54f367b60d55dc19b35ce1b63e0/addon/components/paper-select/ebd-content/component.js#L9
- https://github.com/miguelcobain/ember-paper/blob/0c27d34578027b5260d2151b1c3c6cab26fbd685/addon/components/paper-tooltip-inner.js#L5
- https://github.com/miguelcobain/ember-paper/blob/a910222c1c9c45c4178e4a8050aa8f09067f24bd/addon/mixins/translate3d-mixin.js#L9

**Comment by matthewhartstonge** [comment]
Cool, so the tests look like they are failing due to scope (probably non-explicit this e.t.c).

I'll look at patching that now. :)

> not ok 54 Chrome 129.0 - [42 ms] - Integration | Component | paper-dialog: click outside >should close dialog if clickOutsideToClose
    ---
        stack: >
            Error: Attempted to resolve a value in a strict mode template, but that value was not in scope: dialogOpen
> 
> ...
>
> ok 308 Chrome 129.0 - [0 ms] - Unit | Validator | minlength: falsy values
> ok 309 Chrome 129.0 - [0 ms] - Unit | Validator | required: strings
> ok 310 Chrome 129.0 - [0 ms] - Unit | Validator | required: falsy values
> ok 311 Chrome 129.0 - [0 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly
>
> 1..311
> tests 311
> pass  30
> skip  4
> todo  0
> fail  277

**Comment by mansona** [comment]
So if we get a small pr of yours merged then you won't need me to approve the tests any more.

Maybe extract the ember-css-transition upgrade on its own

**Pull request closed without merging**
